FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY p /usr/share/nginx/html/p
COPY assets /usr/share/nginx/html/assets
COPY partials /usr/share/nginx/html/partials
